services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackathon_db
    ports:
      - "5435:5432" # Host port 5435 -> Container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6381:6379" # Host port 6381 -> Container port 6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
